#sudo: required

os: linux

language: generic

# ----------------------------
# *** 우분투 릴리즈별 코드명  ***
# Xenial Xerus (16.04)
# Yakkety Yak (16.10)
# Zesty Zapus (17.04)
# Artful Aardvark (17.10)
# Bionic Beaver (18.04)
# ----------------------------
dist: xenial

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t korea13135/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true korea13135/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"