sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t korea13135/docker-react-app -f Dockeerfile.dev .

script:
  - docker run -e CI=true korea13135/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"